# Generated by Django 5.1.3 on 2026-09-03 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('grade_letter', models.CharField(max_length=10, verbose_name='Grade Letter')),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Minimum Percentage')),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Maximum Percentage')),
                ('grade_point', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Grade Point')),
                ('remarks', models.CharField(blank=True, default='', max_length=100, verbose_name='Remarks')),
                ('remarks_urdu', models.CharField(blank=True, default='', max_length=100, verbose_name='Remarks (Urdu)')),
            ],
            options={
                'verbose_name': 'Grade Scale',
                'verbose_name_plural': 'Grade Scales',
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Marks Obtained')),
                ('is_absent', models.BooleanField(default=False, verbose_name='Was Absent')),
                ('grade_letter', models.CharField(blank=True, default='', max_length=10, verbose_name='Calculated Grade')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='Teacher Remarks')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_grades', to=settings.AUTH_USER_MODEL)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='examinations.examsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
            options={
                'verbose_name': 'Grade Record',
                'verbose_name_plural': 'Grade Records',
                'indexes': [models.Index(fields=['student', 'exam_subject'], name='grades_grad_student_7a3507_idx')],
                'unique_together': {('exam_subject', 'student')},
            },
        ),
    ]
