# Generated by Django 5.1.3 on 2026-09-03 07:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(default='Jamia Islamia', max_length=255, verbose_name='School Name')),
                ('name_urdu', models.CharField(default='جامعہ اسلامیہ', max_length=255, verbose_name='School Name (Urdu)')),
                ('code', models.CharField(default='JI-BHATKAL', max_length=50, unique=True, verbose_name='School Code')),
                ('address', models.TextField(default='Nawayath Colony, Bhatkal, Karnataka, India', verbose_name='Address')),
                ('address_urdu', models.TextField(default='نوایت کالونی، بھٹکل، کرناٹک، بھارت', verbose_name='Address (Urdu)')),
                ('phone', models.CharField(default='+91 8386 220000', max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(default='info@jamiaislamia.edu', max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, default='https://jamiaislamia.edu.in', verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/', verbose_name='Logo')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='School Settings')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
    ]
