# Generated by Django 5.1.3 on 2026-09-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(default='Bhatkal, Karnataka, India', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address_urdu',
            field=models.TextField(default='بھٹکل، کرناٹک، بھارت', verbose_name='Address (Urdu)'),
        ),
    ]
