# Generated by Django 5.1.3 on 2026-09-03 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('title', models.CharField(max_length=200, verbose_name='Homework Title')),
                ('title_urdu', models.CharField(blank=True, default='', max_length=200, verbose_name='Homework Title (Urdu)')),
                ('description', models.TextField(verbose_name='Detailed Instructions / Content')),
                ('due_date', models.DateField(db_index=True, verbose_name='Due Date')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Worksheet / Material Attachment')),
                ('max_marks', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Maximum Marks')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.classroom')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment / Homework',
                'verbose_name_plural': 'Assignments & Homework',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('submission_text', models.TextField(blank=True, default='', verbose_name='Student Answers / Notes')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Submission File / Photo')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('LATE', 'Late Submission'), ('RESUBMISSION_REQUESTED', 'Resubmission Requested')], default='SUBMITTED', max_length=30, verbose_name='Status')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Marks Awarded')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='Teacher Feedback')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='students.student')),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'ordering': ['-created_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
