# Generated by Django 5.1.3 on 2026-09-03 07:52

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', validators=[core.validators.validate_secure_file_upload], verbose_name='Worksheet / Material Attachment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', validators=[core.validators.validate_secure_file_upload], verbose_name='Submission File / Photo'),
        ),
    ]
