# Generated by Django 5.1.3 on 2026-09-03 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('title', models.CharField(max_length=200, verbose_name='Notification Title')),
                ('title_urdu', models.CharField(blank=True, default='', max_length=200, verbose_name='Notification Title (Urdu)')),
                ('body', models.TextField(verbose_name='Notification Body')),
                ('body_urdu', models.TextField(blank=True, default='', verbose_name='Notification Body (Urdu)')),
                ('notification_type', models.CharField(choices=[('ATTENDANCE', 'Attendance Alert'), ('HOMEWORK', 'Homework / Assignment'), ('EXAM', 'Examination Schedule'), ('GRADE', 'Grade / Result Publication'), ('ANNOUNCEMENT', 'School Announcement'), ('MESSAGE', 'Direct Message'), ('TIMETABLE', 'Timetable Update'), ('SYSTEM', 'System Alert')], db_index=True, default='SYSTEM', max_length=30, verbose_name='Type')),
                ('resource_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Resource Type')),
                ('resource_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Resource ID')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
