# Generated by Django 5.1.3 on 2026-09-03 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('employee_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Employee Code')),
                ('qualification', models.CharField(blank=True, default='', max_length=200, verbose_name='Qualification')),
                ('designation', models.CharField(default='Teacher', max_length=100, verbose_name='Designation')),
                ('department', models.CharField(choices=[('ACADEMIC', 'Academic / Teaching'), ('ADMINISTRATION', 'Administration'), ('ISLAMIC_STUDIES', 'Islamic Studies / Qirat'), ('LIBRARY', 'Library'), ('FINANCE', 'Finance & Accounts'), ('SUPPORT', 'Support & Maintenance')], default='ACADEMIC', max_length=50, verbose_name='Department')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='Date of Joining')),
                ('is_teaching', models.BooleanField(default=True, verbose_name='Is Teaching Staff')),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=100, verbose_name='Emergency Contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff Members',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('reason', models.TextField(verbose_name='Reason for Leave')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Admin Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-start_date'],
            },
        ),
    ]
