# Generated by Django 5.1.3 on 2026-09-03 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(help_text='e.g., 2026-2027', max_length=50, unique=True, verbose_name='Year Name')),
                ('name_urdu', models.CharField(blank=True, default='', max_length=50, verbose_name='Year Name (Urdu)')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, verbose_name='Is Current Academic Year')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('name_urdu', models.CharField(blank=True, default='', max_length=100, verbose_name='Subject Name (Urdu)')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Subject Code')),
                ('is_elective', models.BooleanField(default=False, verbose_name='Is Elective')),
                ('credit_hours', models.PositiveIntegerField(default=4, verbose_name='Credit Hours / Periods per week')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectTeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
            ],
            options={
                'verbose_name': 'Subject Teacher Assignment',
                'verbose_name_plural': 'Subject Teacher Assignments',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=100, verbose_name='Class Name')),
                ('name_urdu', models.CharField(blank=True, default='', max_length=100, verbose_name='Class Name (Urdu)')),
                ('numeric_level', models.PositiveIntegerField(default=1, verbose_name='Numeric Level')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['numeric_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(help_text='e.g., Section A, B', max_length=50, verbose_name='Section Name')),
                ('name_urdu', models.CharField(blank=True, default='', max_length=50, verbose_name='Section Name (Urdu)')),
                ('capacity', models.PositiveIntegerField(default=40, verbose_name='Student Capacity')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academic.classroom')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['class_room__numeric_level', 'name'],
            },
        ),
    ]
