# Generated by Django 5.1.3 on 2026-09-03 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academic.classroom'),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academic.section'),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('class_room', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectteacherassignment',
            unique_together={('academic_year', 'section', 'subject', 'teacher')},
        ),
    ]
