# Generated by Django 5.1.3 on 2026-09-03 07:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('title', models.CharField(max_length=150, verbose_name='Event Title')),
                ('title_urdu', models.CharField(blank=True, default='', max_length=150, verbose_name='Event Title (Urdu)')),
                ('event_type', models.CharField(choices=[('HOLIDAY', 'School Holiday'), ('EXAM', 'Examination'), ('ACADEMIC', 'Academic Milestone / Term Start'), ('MEETING', 'Parent-Teacher Meeting'), ('DEADLINE', 'Assignment / Fee Deadline'), ('SPORTS', 'Sports & Extra-Curricular'), ('ISLAMIC', 'Islamic Event / Gathering')], db_index=True, default='ACADEMIC', max_length=20, verbose_name='Event Type')),
                ('start_date', models.DateField(db_index=True, verbose_name='Start Date')),
                ('end_date', models.DateField(db_index=True, verbose_name='End Date')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('description_urdu', models.TextField(blank=True, default='', verbose_name='Description (Urdu)')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='Is Institutional Holiday')),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['start_date'],
            },
        ),
    ]
