# Generated by Django 5.1.3 on 2026-09-03 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=150, verbose_name='Exam Title')),
                ('name_urdu', models.CharField(blank=True, default='', max_length=150, verbose_name='Exam Title (Urdu)')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Is Results Published')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description / Instructions')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic.academicyear')),
            ],
            options={
                'verbose_name': 'Examination',
                'verbose_name_plural': 'Examinations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('exam_date', models.DateField(verbose_name='Exam Date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Total Marks')),
                ('passing_marks', models.DecimalField(decimal_places=2, default=40.0, max_digits=5, verbose_name='Passing Marks')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='academic.classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='examinations.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Exam Subject Schedule',
                'verbose_name_plural': 'Exam Subject Schedules',
                'ordering': ['exam_date', 'start_time'],
                'unique_together': {('exam', 'class_room', 'subject')},
            },
        ),
    ]
