# Generated by Django 5.1.3 on 2026-09-03 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('father_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Father Name')),
                ('father_name_urdu', models.CharField(blank=True, default='', max_length=150, verbose_name='Father Name (Urdu)')),
                ('mother_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Mother Name')),
                ('mother_name_urdu', models.CharField(blank=True, default='', max_length=150, verbose_name='Mother Name (Urdu)')),
                ('primary_phone', models.CharField(max_length=50, verbose_name='Primary Phone Number')),
                ('secondary_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Secondary Phone Number')),
                ('occupation', models.CharField(blank=True, default='', max_length=100, verbose_name='Occupation')),
                ('address', models.TextField(blank=True, default='', verbose_name='Residential Address')),
                ('address_urdu', models.TextField(blank=True, default='', verbose_name='Residential Address (Urdu)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
        ),
        migrations.CreateModel(
            name='ParentStudentRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('relationship_type', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Guardian')], default='FATHER', max_length=20, verbose_name='Relationship Type')),
                ('is_primary_contact', models.BooleanField(default=True, verbose_name='Is Primary Contact')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to='parents.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='students.student')),
            ],
            options={
                'verbose_name': 'Parent Student Link',
                'verbose_name_plural': 'Parent Student Links',
                'unique_together': {('parent', 'student')},
            },
        ),
    ]
