# Generated by Django 5.1.3 on 2026-09-03 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('request_path', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=10)),
                ('request_hash', models.CharField(max_length=64)),
                ('status_code', models.IntegerField()),
                ('response_body', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'user'], name='accounts_id_key_55b2c3_idx')],
                'unique_together': {('key', 'user')},
            },
        ),
    ]
