# Generated by Django 5.1.3 on 2026-09-03 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_urdu', models.CharField(blank=True, default='', max_length=200, verbose_name='Title (Urdu)')),
                ('content', models.TextField(verbose_name='Announcement Content')),
                ('content_urdu', models.TextField(blank=True, default='', verbose_name='Announcement Content (Urdu)')),
                ('audience', models.CharField(choices=[('ALL', 'School-wide (Everyone)'), ('TEACHERS', 'Teachers Only'), ('STUDENTS', 'Students Only'), ('PARENTS', 'Parents Only'), ('CLASS', 'Specific Class / Section')], default='ALL', max_length=20, verbose_name='Target Audience')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/', verbose_name='Attachment')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Is Pinned Announcement')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publish Date')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiry Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academic.classroom')),
                ('target_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academic.section')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
    ]
