# Generated by Django 5.1.3 on 2026-09-03 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('admission_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Admission Number')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('first_name_urdu', models.CharField(blank=True, default='', max_length=100, verbose_name='First Name (Urdu)')),
                ('last_name_urdu', models.CharField(blank=True, default='', max_length=100, verbose_name='Last Name (Urdu)')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('blood_group', models.CharField(blank=True, default='', max_length=10, verbose_name='Blood Group')),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Emergency Contact Phone')),
                ('address', models.TextField(blank=True, default='', verbose_name='Residential Address')),
                ('address_urdu', models.TextField(blank=True, default='', verbose_name='Residential Address (Urdu)')),
                ('previous_school', models.CharField(blank=True, default='', max_length=255, verbose_name='Previous School')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRANSFERRED', 'Transferred'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Status')),
                ('admission_date', models.DateField(auto_now_add=True, verbose_name='Admission Date')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['admission_number'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('roll_number', models.CharField(blank=True, default='', max_length=30, verbose_name='Roll Number')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Enrollment Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active Enrollment')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.academicyear')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.classroom')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['class_room__numeric_level', 'section__name', 'roll_number'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
